# robot_control stop diagnostics
# robot_control restart diagnostics
# bag包记录

parameters:
  # ========== 控制频率 ==========
  RLFrequency: 50  # Hz
  yawKp: 0.8

  # ========== Topic配置 ==========
  lowStateTopic: "/robot/state"              # 硬件信息topic 包含电机数据 IMU数据
  jointCommandsTopic: "/motor_control/motor_control"  # 电机命令topic
  joyTopic: "/joy"                           # 手柄topic

  # ========== 电机配置 ==========
  robotJointNum: 26                          # 总关节数
  policyJointNum: 12                         # Policy控制的关节数
  
  # Policy控制的关节索引（前12个关节）
  policy_joint_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  #腰部 yaw roll pitch  实际现在机器人电机是 left right yaw
  # ========== ONNX模型 ========== policy_12
  onnx_path: "policy_lk_15.onnx"
#   onnx_path: "policy_12.onnx"
  # ========== 观测向量配置 ==========
  observation_dim: 47  # 总观测维度47
  
  # 观测缩放因子
  ang_vel_scale: 0.25       # 角速度缩放
  joint_vel_scale: 0.05     # 关节速度缩放
  vel_cmd_scale: [2.0, 2.0, 0.25]  # 速度命令缩放[x, y, yaw]

  # ========== 动作缩放配置（26个电机）==========
  # Policy输出 * action_scale + defaultPos = 最终位置命令
  action_scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25]

  # ========== PD增益（26个电机）==========  120 1  200 5
  kps: [680.0, 450.0, 450.0, 680.0, 220.0, 220.0, 
        680.0, 450.0, 450.0, 680.0, 220.0, 220.0, 
        600.0, 600.0, 2000.0, 
        200.0, 50.0, 50.0, 50.0, 50.0, 
        200.0, 50.0, 50.0, 50.0, 50.0, 
        0.0]
  kds: [40.0, 25.0, 25.0, 30.0, 10.0, 10.0, 
        40.0, 25.0, 25.0, 30.0, 10.0, 10.0, 
        20.0, 20.0, 50.0, 
        20.0, 20.0, 20.0, 20.0, 20.0, 
        20.0, 20.0, 20.0, 20.0, 20.0, 
        5.0]
#   kps: [1000.0, 600.0, 600.0, 1000.0, 400.0, 400.0, 
#         1000.0, 600.0, 600.0, 1000.0, 400.0, 400.0, 
#         0.0, 0.0, 2000.0, 
#         200.0, 50.0, 50.0, 50.0, 50.0, 
#         200.0, 50.0, 50.0, 50.0, 50.0, 
#         0.0]
#   kds: [50.0, 30.0, 30.0, 50.0, 20.0, 20.0, 
#         50.0, 30.0, 30.0, 50.0, 20.0, 20.0, 
#         0.0, 0.0, 50.0, 
#         20.0, 20.0, 20.0, 20.0, 20.0, 
#         20.0, 20.0, 20.0, 20.0, 20.0, 
#         5.0]
        
  rkps: [2000.0, 2000.0, 2000.0, 2000.0, 600.0, 600.0, 
        2000.0, 2000.0, 2000.0, 2000.0, 600.0, 600.0,
        600.0, 600.0, 2000.0, 
        50.0, 50.0, 50, 50.0, 50.0, 
        50.0, 50.0, 50.0, 50.0, 50.0, 
        0.0]
  rkds: [50.0, 50.0, 50.0, 50.0, 20.0, 20.0, 
        50.0, 50.0, 50.0, 50.0, 20.0, 20.0,
        20.0, 20.0, 50.0, 
        20.0, 20.0, 20.0, 20.0, 20.0, 
        20.0, 20.0, 20.0, 20.0, 20.0, 
        5.0]
  # ========== 默认站立位置（26个电机）==========
#   defaultPos: [-0.2, 0.0, 0.0, 0.4, -0.20, 0.0, 
#                -0.2, 0.0, -0.0, 0.4, -0.20, 0.0, 
#                0.0, 0.0, 0.0, 
#                0.0, 0.2, 0.0, 1.0, 0.0, 
#                0.0, -0.2, 0.0, 1.0, 0.0, 
#                0.0]
#   readyPos: [-0.2, 0.0, 0.0, 0.4, -0.30, 0.0, 
#              -0.2, 0.0, -0.0, 0.4, -0.30, 0.0, 
#               0.0, 0.0, 0.0, 
#               0.0, 0.2, 0.0, 1.0, 0.0, 
#               0.0, -0.2, 0.0, 1.0, 0.0, 
#               0.0]  
  defaultPos: [-0.2, 0.0, 0.0, 0.4, -0.20, 0.0, 
               -0.2, 0.0, -0.0, 0.4, -0.20, 0.0, 
               0.0, 0.0, 0.0, 
               0.0, 0.0, 0.0, 0.0, 0.0, 
               0.0, -0.0, 0.0, 0.0, 0.0, 
               0.0]
  readyPos: [-0.2, 0.0, 0.0, 0.4, -0.30, 0.0, 
             -0.2, 0.0, -0.0, 0.4, -0.30, 0.0, 
              0.0, 0.0, 0.0, 
              0.0, 0.0, 0.0, 0.0, 0.0, 
              0.0, -0.0, 0.0, 0.0, 0.0, 
              0.0]


  # ========== 状态机配置 ==========
  FSMFlag: 1  # 0: 默认TROT, 1: 手柄控制, 2: 其他模式
  default_state: "STATE_DISABLED"

  # ========== 速度命令限制 ==========
  CommandLimit: [0.8, 0.5, 0.75]    # x, y, yaw速度命令范围绝对值
  CommandOffset: [0.0, 0.0, 0.0]  # x, y, yaw速度命令偏置
  vel_ramp_decel: [0.6, 0.5]      # 减速斜坡限制 [x, y] m/s²

  # ========== 手柄配置 ==========
  JoyType: 0  # 0: Xinput手柄, 1: 北通飞智手柄

  # ========== 调试配置 ==========
  ShowLog: 1             # 是否显示详细日志
  enable_logging: false  # 是否启用日志记录


#   #腰部死区
#   yaw_motor_index: 14           # 腰部yaw电机索引
#   yaw_dead_zone: 0.03           # 死区阈值（弧度，0.03≈1.7°）
#   yaw_dead_zone_kd: 100.0        # 死区内的阻尼kd
