# robot_control stop diagnostics
# robot_control restart diagnostics
# bag包记录

parameters:
  # ========== 控制频率 ==========
  RLFrequency: 50  # Hz
  yawKp: 0.8

  # ========== Topic配置 ==========
  lowStateTopic: "/robot/state"              # 硬件信息topic 包含电机数据 IMU数据
  jointCommandsTopic: "/motor_control/motor_control"  # 电机命令topic
  joyTopic: "/joy"                           # 手柄topic

  # ========== 电机配置 ==========
  robotJointNum: 26                          # 总关节数
  policyJointNum: 15                         # Policy控制的关节数（12腿部 + 3腰部）
  
  # policy_joint_indices[i] = 硬件电机索引, i = policy索引
  policy_joint_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 12, 13]
  # ========== ONNX模型 ==========
  algo_config_dir: "/app/etc/algo"
  onnx_path: "x_15/policy_d15_4.onnx"
  # ========== 观测向量配置 ==========
  observation_dim: 56 
  
  # 观测缩放因子
  ang_vel_scale: 0.25       # 角速度缩放
  joint_vel_scale: 0.05     # 关节速度缩放
  vel_cmd_scale: [1.00, 1.00, 1.00]  # 速度命令缩放[x, y, yaw]
  # ========== 动作缩放配置（26个电机）==========
  # Policy输出 * action_scale + defaultPos = 最终位置命令
  action_scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.0]

  # ========== PD增益（26个电机）==========  120 1  200 5
  kps: [850.0, 800.0, 600.0, 800.0, 220.0, 220.0, 
        850.0, 800.0, 600.0, 800.0, 220.0, 220.0, 
        600.0, 600.0, 2000.0, 
        200.0, 50.0, 50.0, 50.0, 50.0, 
        200.0, 50.0, 50.0, 50.0, 50.0, 
        0.0]
  kds: [40.0, 40.0, 35.0, 40.0, 10.0, 10.0, 
        40.0, 40.0, 35.0, 40.0, 10.0, 10.0, 
        25.0, 25.0, 50.0, 
        20.0, 20.0, 20.0, 20.0, 20.0, 
        20.0, 20.0, 20.0, 20.0, 20.0, 
        5.0]
  rkps: [2000.0, 2000.0, 2000.0, 2000.0, 600.0, 600.0, 
        2000.0, 2000.0, 2000.0, 2000.0, 600.0, 600.0,
        600.0, 600.0, 2000.0, 
        50, 50.0, 50, 50.0, 50.0, 
        50.0, 50.0, 50.0, 50.0, 50.0, 
        0.0]
  rkds: [50.0, 50.0, 50.0, 50.0, 20.0, 20.0, 
        50.0, 50.0, 50.0, 50.0, 20.0, 20.0,
        30.0, 30.0, 50.0, 
        20.0, 20.0, 20.0, 20.0, 20.0, 
        20.0, 20.0, 20.0, 20.0, 20.0, 
        5.0]
  # ========== 默认站立位置（26个电机）==========
  defaultPos: [-0.2, 0.0, 0.0, 0.4, -0.20, 0.0, 
               -0.2, 0.0, -0.0, 0.4, -0.20, 0.0, 
               0.0, 0.0, 0.0, 
               0.0, 0.3, 0.0, 1.0, 0.0, 
               0.0, -0.3, 0.0, 1.0, 0.0, 
               0.0]
  readyPos: [-0.2, 0.0, 0.0, 0.4, -0.30, 0.0, 
             -0.2, 0.0, -0.0, 0.4, -0.30, 0.0, 
              0.0, 0.0, 0.0, 
              0.0, 0.3, 0.0, 1.0, 0.0, 
              0.0, -0.3, 0.0, 1.0, 0.0, 
              0.0] 
  # ========== 状态机配置 ==========
  FSMFlag: 1  # 0: 默认TROT, 1: 手柄控制, 2: 其他模式
  default_state: "STATE_DISABLED"

  # ========== 速度命令限制 ==========
  CommandLimit: [0.8, 0.25, 0.6]    # x, y, yaw速度命令范围绝对值
  CommandOffset: [0.0, 0.0, 0.0]  # x, y, yaw速度命令偏置
  vel_ramp_decel: [0.6, 0.5]      # 减速斜坡限制 [x, y] m/s²

  # ========== 手柄配置 ==========
  JoyType: 0  # 0: Xinput手柄

  # ========== 调试配置 ==========
  ShowLog: 1             # 是否显示详细日志
  enable_logging: false  # 是否启用日志记录
